services:
  opp-service:
    image: 528573161741.dkr.ecr.ap-southeast-1.amazonaws.com/opp-service:v1.0.0
    container_name: opp-service
    restart: always
    environment:
      profile: dev
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      DB_URL: jdbc:mysql://mysql-bdb-jup-database.c0zrisx5dzle.ap-southeast-1.rds.amazonaws.com:3306/jupiter
      DB_USERNAME: bdbjupAdmin
      DB_PASSWORD: bdbJupiter123
      SWAGGER.BASEURL: "api-hub.bdb-jup.com/jupiter"
      SERVER.PORT: 8081
    networks:
      - jup_docker_network
    build: .
    ports:
      - 8081:8081

networks:
  jup_docker_network:
    external: true