# Config port
server:
  port: 8081

# Config service client
eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
  client:
    fetchRegistry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Config local database connection
spring:
  application:
    name: opps-service
  datasource:
    url: jdbc:mysql://localhost:3306/jupiter?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true


# Show sql
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# swagger
springdoc:
  api-docs:
    path: /api-docs
