# Config port
server:
  port: 8081

# Config service client
eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
  client:
    fetchRegistry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://locahost:8761/eureka

# Config database connection
spring:
  application:
    name: opps-service
  datasource:
    url: jdbc:mysql://mysql-bdb-jup-database.c0zrisx5dzle.ap-southeast-1.rds.amazonaws.com:3306/jupiter?createDatabaseIfNotExist=true
    username: bdbjupAdmin
    password: ${password}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Show sql
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# swagger
springdoc:
  api-docs:
    path: /api-docs
