# Config port
server:
  port: ${SERVER.PORT}

# Config service client
eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
  client:
    fetchRegistry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.DEFAULTZONE}

# Config database connection
spring:
  application:
    name: opps-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Show sql
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# swagger
springdoc:
  api-docs:
    path: /api-docs
---
swagger:
  baseUrl: ${SWAGGER.BASEURL}